name: Awakenings PA
favicon: null
layout_spectrum: 0.9525027668569237
typography_spectrum: 0.7339253823738545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7898157893214375
  lightness: 0.47947629378177226
  saturation: 0.9112075914163142
  rhythmicContrast: 0.9569843716453761
purpose: []
